# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /vol/home/s1935534/Documents/Programms/cmake-3.23.1-linux-x86_64/bin/cmake

# The command to remove a file.
RM = /vol/home/s1935534/Documents/Programms/cmake-3.23.1-linux-x86_64/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /vol/home/s1935534/Documents/BSP/CGSynch

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /vol/home/s1935534/Documents/BSP/CGSynch

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/vol/home/s1935534/Documents/Programms/cmake-3.23.1-linux-x86_64/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/vol/home/s1935534/Documents/Programms/cmake-3.23.1-linux-x86_64/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /vol/home/s1935534/Documents/BSP/CGSynch/CMakeFiles /vol/home/s1935534/Documents/BSP/CGSynch//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /vol/home/s1935534/Documents/BSP/CGSynch/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CGSynch_2

# Build rule for target.
CGSynch_2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CGSynch_2
.PHONY : CGSynch_2

# fast build rule for target.
CGSynch_2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGSynch_2.dir/build.make CMakeFiles/CGSynch_2.dir/build
.PHONY : CGSynch_2/fast

AbstractGame/CombinatorialGame.o: AbstractGame/CombinatorialGame.cpp.o
.PHONY : AbstractGame/CombinatorialGame.o

# target to build an object file
AbstractGame/CombinatorialGame.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGSynch_2.dir/build.make CMakeFiles/CGSynch_2.dir/AbstractGame/CombinatorialGame.cpp.o
.PHONY : AbstractGame/CombinatorialGame.cpp.o

AbstractGame/CombinatorialGame.i: AbstractGame/CombinatorialGame.cpp.i
.PHONY : AbstractGame/CombinatorialGame.i

# target to preprocess a source file
AbstractGame/CombinatorialGame.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGSynch_2.dir/build.make CMakeFiles/CGSynch_2.dir/AbstractGame/CombinatorialGame.cpp.i
.PHONY : AbstractGame/CombinatorialGame.cpp.i

AbstractGame/CombinatorialGame.s: AbstractGame/CombinatorialGame.cpp.s
.PHONY : AbstractGame/CombinatorialGame.s

# target to generate assembly for a file
AbstractGame/CombinatorialGame.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGSynch_2.dir/build.make CMakeFiles/CGSynch_2.dir/AbstractGame/CombinatorialGame.cpp.s
.PHONY : AbstractGame/CombinatorialGame.cpp.s

AbstractGame/CombinatorialGameDatabase.o: AbstractGame/CombinatorialGameDatabase.cpp.o
.PHONY : AbstractGame/CombinatorialGameDatabase.o

# target to build an object file
AbstractGame/CombinatorialGameDatabase.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGSynch_2.dir/build.make CMakeFiles/CGSynch_2.dir/AbstractGame/CombinatorialGameDatabase.cpp.o
.PHONY : AbstractGame/CombinatorialGameDatabase.cpp.o

AbstractGame/CombinatorialGameDatabase.i: AbstractGame/CombinatorialGameDatabase.cpp.i
.PHONY : AbstractGame/CombinatorialGameDatabase.i

# target to preprocess a source file
AbstractGame/CombinatorialGameDatabase.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGSynch_2.dir/build.make CMakeFiles/CGSynch_2.dir/AbstractGame/CombinatorialGameDatabase.cpp.i
.PHONY : AbstractGame/CombinatorialGameDatabase.cpp.i

AbstractGame/CombinatorialGameDatabase.s: AbstractGame/CombinatorialGameDatabase.cpp.s
.PHONY : AbstractGame/CombinatorialGameDatabase.s

# target to generate assembly for a file
AbstractGame/CombinatorialGameDatabase.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGSynch_2.dir/build.make CMakeFiles/CGSynch_2.dir/AbstractGame/CombinatorialGameDatabase.cpp.s
.PHONY : AbstractGame/CombinatorialGameDatabase.cpp.s

AbstractGame/DyadicRational.o: AbstractGame/DyadicRational.cpp.o
.PHONY : AbstractGame/DyadicRational.o

# target to build an object file
AbstractGame/DyadicRational.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGSynch_2.dir/build.make CMakeFiles/CGSynch_2.dir/AbstractGame/DyadicRational.cpp.o
.PHONY : AbstractGame/DyadicRational.cpp.o

AbstractGame/DyadicRational.i: AbstractGame/DyadicRational.cpp.i
.PHONY : AbstractGame/DyadicRational.i

# target to preprocess a source file
AbstractGame/DyadicRational.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGSynch_2.dir/build.make CMakeFiles/CGSynch_2.dir/AbstractGame/DyadicRational.cpp.i
.PHONY : AbstractGame/DyadicRational.cpp.i

AbstractGame/DyadicRational.s: AbstractGame/DyadicRational.cpp.s
.PHONY : AbstractGame/DyadicRational.s

# target to generate assembly for a file
AbstractGame/DyadicRational.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGSynch_2.dir/build.make CMakeFiles/CGSynch_2.dir/AbstractGame/DyadicRational.cpp.s
.PHONY : AbstractGame/DyadicRational.cpp.s

AbstractGame/SynchronizedGameDatabase.o: AbstractGame/SynchronizedGameDatabase.cpp.o
.PHONY : AbstractGame/SynchronizedGameDatabase.o

# target to build an object file
AbstractGame/SynchronizedGameDatabase.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGSynch_2.dir/build.make CMakeFiles/CGSynch_2.dir/AbstractGame/SynchronizedGameDatabase.cpp.o
.PHONY : AbstractGame/SynchronizedGameDatabase.cpp.o

AbstractGame/SynchronizedGameDatabase.i: AbstractGame/SynchronizedGameDatabase.cpp.i
.PHONY : AbstractGame/SynchronizedGameDatabase.i

# target to preprocess a source file
AbstractGame/SynchronizedGameDatabase.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGSynch_2.dir/build.make CMakeFiles/CGSynch_2.dir/AbstractGame/SynchronizedGameDatabase.cpp.i
.PHONY : AbstractGame/SynchronizedGameDatabase.cpp.i

AbstractGame/SynchronizedGameDatabase.s: AbstractGame/SynchronizedGameDatabase.cpp.s
.PHONY : AbstractGame/SynchronizedGameDatabase.s

# target to generate assembly for a file
AbstractGame/SynchronizedGameDatabase.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGSynch_2.dir/build.make CMakeFiles/CGSynch_2.dir/AbstractGame/SynchronizedGameDatabase.cpp.s
.PHONY : AbstractGame/SynchronizedGameDatabase.cpp.s

AbstractGame/SynchronousGame.o: AbstractGame/SynchronousGame.cpp.o
.PHONY : AbstractGame/SynchronousGame.o

# target to build an object file
AbstractGame/SynchronousGame.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGSynch_2.dir/build.make CMakeFiles/CGSynch_2.dir/AbstractGame/SynchronousGame.cpp.o
.PHONY : AbstractGame/SynchronousGame.cpp.o

AbstractGame/SynchronousGame.i: AbstractGame/SynchronousGame.cpp.i
.PHONY : AbstractGame/SynchronousGame.i

# target to preprocess a source file
AbstractGame/SynchronousGame.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGSynch_2.dir/build.make CMakeFiles/CGSynch_2.dir/AbstractGame/SynchronousGame.cpp.i
.PHONY : AbstractGame/SynchronousGame.cpp.i

AbstractGame/SynchronousGame.s: AbstractGame/SynchronousGame.cpp.s
.PHONY : AbstractGame/SynchronousGame.s

# target to generate assembly for a file
AbstractGame/SynchronousGame.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGSynch_2.dir/build.make CMakeFiles/CGSynch_2.dir/AbstractGame/SynchronousGame.cpp.s
.PHONY : AbstractGame/SynchronousGame.cpp.s

CombinatorialGames/Cherries/Cherries.o: CombinatorialGames/Cherries/Cherries.cpp.o
.PHONY : CombinatorialGames/Cherries/Cherries.o

# target to build an object file
CombinatorialGames/Cherries/Cherries.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGSynch_2.dir/build.make CMakeFiles/CGSynch_2.dir/CombinatorialGames/Cherries/Cherries.cpp.o
.PHONY : CombinatorialGames/Cherries/Cherries.cpp.o

CombinatorialGames/Cherries/Cherries.i: CombinatorialGames/Cherries/Cherries.cpp.i
.PHONY : CombinatorialGames/Cherries/Cherries.i

# target to preprocess a source file
CombinatorialGames/Cherries/Cherries.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGSynch_2.dir/build.make CMakeFiles/CGSynch_2.dir/CombinatorialGames/Cherries/Cherries.cpp.i
.PHONY : CombinatorialGames/Cherries/Cherries.cpp.i

CombinatorialGames/Cherries/Cherries.s: CombinatorialGames/Cherries/Cherries.cpp.s
.PHONY : CombinatorialGames/Cherries/Cherries.s

# target to generate assembly for a file
CombinatorialGames/Cherries/Cherries.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGSynch_2.dir/build.make CMakeFiles/CGSynch_2.dir/CombinatorialGames/Cherries/Cherries.cpp.s
.PHONY : CombinatorialGames/Cherries/Cherries.cpp.s

CombinatorialGames/Cherries/CherriesUtil.o: CombinatorialGames/Cherries/CherriesUtil.cpp.o
.PHONY : CombinatorialGames/Cherries/CherriesUtil.o

# target to build an object file
CombinatorialGames/Cherries/CherriesUtil.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGSynch_2.dir/build.make CMakeFiles/CGSynch_2.dir/CombinatorialGames/Cherries/CherriesUtil.cpp.o
.PHONY : CombinatorialGames/Cherries/CherriesUtil.cpp.o

CombinatorialGames/Cherries/CherriesUtil.i: CombinatorialGames/Cherries/CherriesUtil.cpp.i
.PHONY : CombinatorialGames/Cherries/CherriesUtil.i

# target to preprocess a source file
CombinatorialGames/Cherries/CherriesUtil.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGSynch_2.dir/build.make CMakeFiles/CGSynch_2.dir/CombinatorialGames/Cherries/CherriesUtil.cpp.i
.PHONY : CombinatorialGames/Cherries/CherriesUtil.cpp.i

CombinatorialGames/Cherries/CherriesUtil.s: CombinatorialGames/Cherries/CherriesUtil.cpp.s
.PHONY : CombinatorialGames/Cherries/CherriesUtil.s

# target to generate assembly for a file
CombinatorialGames/Cherries/CherriesUtil.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGSynch_2.dir/build.make CMakeFiles/CGSynch_2.dir/CombinatorialGames/Cherries/CherriesUtil.cpp.s
.PHONY : CombinatorialGames/Cherries/CherriesUtil.cpp.s

CombinatorialGames/Cherries/StackCherries.o: CombinatorialGames/Cherries/StackCherries.cpp.o
.PHONY : CombinatorialGames/Cherries/StackCherries.o

# target to build an object file
CombinatorialGames/Cherries/StackCherries.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGSynch_2.dir/build.make CMakeFiles/CGSynch_2.dir/CombinatorialGames/Cherries/StackCherries.cpp.o
.PHONY : CombinatorialGames/Cherries/StackCherries.cpp.o

CombinatorialGames/Cherries/StackCherries.i: CombinatorialGames/Cherries/StackCherries.cpp.i
.PHONY : CombinatorialGames/Cherries/StackCherries.i

# target to preprocess a source file
CombinatorialGames/Cherries/StackCherries.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGSynch_2.dir/build.make CMakeFiles/CGSynch_2.dir/CombinatorialGames/Cherries/StackCherries.cpp.i
.PHONY : CombinatorialGames/Cherries/StackCherries.cpp.i

CombinatorialGames/Cherries/StackCherries.s: CombinatorialGames/Cherries/StackCherries.cpp.s
.PHONY : CombinatorialGames/Cherries/StackCherries.s

# target to generate assembly for a file
CombinatorialGames/Cherries/StackCherries.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGSynch_2.dir/build.make CMakeFiles/CGSynch_2.dir/CombinatorialGames/Cherries/StackCherries.cpp.s
.PHONY : CombinatorialGames/Cherries/StackCherries.cpp.s

CombinatorialGames/Hackenbush/Hackenbush.o: CombinatorialGames/Hackenbush/Hackenbush.cpp.o
.PHONY : CombinatorialGames/Hackenbush/Hackenbush.o

# target to build an object file
CombinatorialGames/Hackenbush/Hackenbush.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGSynch_2.dir/build.make CMakeFiles/CGSynch_2.dir/CombinatorialGames/Hackenbush/Hackenbush.cpp.o
.PHONY : CombinatorialGames/Hackenbush/Hackenbush.cpp.o

CombinatorialGames/Hackenbush/Hackenbush.i: CombinatorialGames/Hackenbush/Hackenbush.cpp.i
.PHONY : CombinatorialGames/Hackenbush/Hackenbush.i

# target to preprocess a source file
CombinatorialGames/Hackenbush/Hackenbush.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGSynch_2.dir/build.make CMakeFiles/CGSynch_2.dir/CombinatorialGames/Hackenbush/Hackenbush.cpp.i
.PHONY : CombinatorialGames/Hackenbush/Hackenbush.cpp.i

CombinatorialGames/Hackenbush/Hackenbush.s: CombinatorialGames/Hackenbush/Hackenbush.cpp.s
.PHONY : CombinatorialGames/Hackenbush/Hackenbush.s

# target to generate assembly for a file
CombinatorialGames/Hackenbush/Hackenbush.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGSynch_2.dir/build.make CMakeFiles/CGSynch_2.dir/CombinatorialGames/Hackenbush/Hackenbush.cpp.s
.PHONY : CombinatorialGames/Hackenbush/Hackenbush.cpp.s

CombinatorialGames/Hackenbush/NormalGraph.o: CombinatorialGames/Hackenbush/NormalGraph.cpp.o
.PHONY : CombinatorialGames/Hackenbush/NormalGraph.o

# target to build an object file
CombinatorialGames/Hackenbush/NormalGraph.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGSynch_2.dir/build.make CMakeFiles/CGSynch_2.dir/CombinatorialGames/Hackenbush/NormalGraph.cpp.o
.PHONY : CombinatorialGames/Hackenbush/NormalGraph.cpp.o

CombinatorialGames/Hackenbush/NormalGraph.i: CombinatorialGames/Hackenbush/NormalGraph.cpp.i
.PHONY : CombinatorialGames/Hackenbush/NormalGraph.i

# target to preprocess a source file
CombinatorialGames/Hackenbush/NormalGraph.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGSynch_2.dir/build.make CMakeFiles/CGSynch_2.dir/CombinatorialGames/Hackenbush/NormalGraph.cpp.i
.PHONY : CombinatorialGames/Hackenbush/NormalGraph.cpp.i

CombinatorialGames/Hackenbush/NormalGraph.s: CombinatorialGames/Hackenbush/NormalGraph.cpp.s
.PHONY : CombinatorialGames/Hackenbush/NormalGraph.s

# target to generate assembly for a file
CombinatorialGames/Hackenbush/NormalGraph.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGSynch_2.dir/build.make CMakeFiles/CGSynch_2.dir/CombinatorialGames/Hackenbush/NormalGraph.cpp.s
.PHONY : CombinatorialGames/Hackenbush/NormalGraph.cpp.s

CombinatorialGames/Math/RulesetMath.o: CombinatorialGames/Math/RulesetMath.cpp.o
.PHONY : CombinatorialGames/Math/RulesetMath.o

# target to build an object file
CombinatorialGames/Math/RulesetMath.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGSynch_2.dir/build.make CMakeFiles/CGSynch_2.dir/CombinatorialGames/Math/RulesetMath.cpp.o
.PHONY : CombinatorialGames/Math/RulesetMath.cpp.o

CombinatorialGames/Math/RulesetMath.i: CombinatorialGames/Math/RulesetMath.cpp.i
.PHONY : CombinatorialGames/Math/RulesetMath.i

# target to preprocess a source file
CombinatorialGames/Math/RulesetMath.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGSynch_2.dir/build.make CMakeFiles/CGSynch_2.dir/CombinatorialGames/Math/RulesetMath.cpp.i
.PHONY : CombinatorialGames/Math/RulesetMath.cpp.i

CombinatorialGames/Math/RulesetMath.s: CombinatorialGames/Math/RulesetMath.cpp.s
.PHONY : CombinatorialGames/Math/RulesetMath.s

# target to generate assembly for a file
CombinatorialGames/Math/RulesetMath.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGSynch_2.dir/build.make CMakeFiles/CGSynch_2.dir/CombinatorialGames/Math/RulesetMath.cpp.s
.PHONY : CombinatorialGames/Math/RulesetMath.cpp.s

CombinatorialGames/Math/RulesetMathUtil.o: CombinatorialGames/Math/RulesetMathUtil.cpp.o
.PHONY : CombinatorialGames/Math/RulesetMathUtil.o

# target to build an object file
CombinatorialGames/Math/RulesetMathUtil.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGSynch_2.dir/build.make CMakeFiles/CGSynch_2.dir/CombinatorialGames/Math/RulesetMathUtil.cpp.o
.PHONY : CombinatorialGames/Math/RulesetMathUtil.cpp.o

CombinatorialGames/Math/RulesetMathUtil.i: CombinatorialGames/Math/RulesetMathUtil.cpp.i
.PHONY : CombinatorialGames/Math/RulesetMathUtil.i

# target to preprocess a source file
CombinatorialGames/Math/RulesetMathUtil.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGSynch_2.dir/build.make CMakeFiles/CGSynch_2.dir/CombinatorialGames/Math/RulesetMathUtil.cpp.i
.PHONY : CombinatorialGames/Math/RulesetMathUtil.cpp.i

CombinatorialGames/Math/RulesetMathUtil.s: CombinatorialGames/Math/RulesetMathUtil.cpp.s
.PHONY : CombinatorialGames/Math/RulesetMathUtil.s

# target to generate assembly for a file
CombinatorialGames/Math/RulesetMathUtil.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGSynch_2.dir/build.make CMakeFiles/CGSynch_2.dir/CombinatorialGames/Math/RulesetMathUtil.cpp.s
.PHONY : CombinatorialGames/Math/RulesetMathUtil.cpp.s

CombinatorialGames/Push-Shove/Push.o: CombinatorialGames/Push-Shove/Push.cpp.o
.PHONY : CombinatorialGames/Push-Shove/Push.o

# target to build an object file
CombinatorialGames/Push-Shove/Push.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGSynch_2.dir/build.make CMakeFiles/CGSynch_2.dir/CombinatorialGames/Push-Shove/Push.cpp.o
.PHONY : CombinatorialGames/Push-Shove/Push.cpp.o

CombinatorialGames/Push-Shove/Push.i: CombinatorialGames/Push-Shove/Push.cpp.i
.PHONY : CombinatorialGames/Push-Shove/Push.i

# target to preprocess a source file
CombinatorialGames/Push-Shove/Push.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGSynch_2.dir/build.make CMakeFiles/CGSynch_2.dir/CombinatorialGames/Push-Shove/Push.cpp.i
.PHONY : CombinatorialGames/Push-Shove/Push.cpp.i

CombinatorialGames/Push-Shove/Push.s: CombinatorialGames/Push-Shove/Push.cpp.s
.PHONY : CombinatorialGames/Push-Shove/Push.s

# target to generate assembly for a file
CombinatorialGames/Push-Shove/Push.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGSynch_2.dir/build.make CMakeFiles/CGSynch_2.dir/CombinatorialGames/Push-Shove/Push.cpp.s
.PHONY : CombinatorialGames/Push-Shove/Push.cpp.s

CombinatorialGames/Push-Shove/PushShoveUtil.o: CombinatorialGames/Push-Shove/PushShoveUtil.cpp.o
.PHONY : CombinatorialGames/Push-Shove/PushShoveUtil.o

# target to build an object file
CombinatorialGames/Push-Shove/PushShoveUtil.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGSynch_2.dir/build.make CMakeFiles/CGSynch_2.dir/CombinatorialGames/Push-Shove/PushShoveUtil.cpp.o
.PHONY : CombinatorialGames/Push-Shove/PushShoveUtil.cpp.o

CombinatorialGames/Push-Shove/PushShoveUtil.i: CombinatorialGames/Push-Shove/PushShoveUtil.cpp.i
.PHONY : CombinatorialGames/Push-Shove/PushShoveUtil.i

# target to preprocess a source file
CombinatorialGames/Push-Shove/PushShoveUtil.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGSynch_2.dir/build.make CMakeFiles/CGSynch_2.dir/CombinatorialGames/Push-Shove/PushShoveUtil.cpp.i
.PHONY : CombinatorialGames/Push-Shove/PushShoveUtil.cpp.i

CombinatorialGames/Push-Shove/PushShoveUtil.s: CombinatorialGames/Push-Shove/PushShoveUtil.cpp.s
.PHONY : CombinatorialGames/Push-Shove/PushShoveUtil.s

# target to generate assembly for a file
CombinatorialGames/Push-Shove/PushShoveUtil.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGSynch_2.dir/build.make CMakeFiles/CGSynch_2.dir/CombinatorialGames/Push-Shove/PushShoveUtil.cpp.s
.PHONY : CombinatorialGames/Push-Shove/PushShoveUtil.cpp.s

CombinatorialGames/Push-Shove/Shove.o: CombinatorialGames/Push-Shove/Shove.cpp.o
.PHONY : CombinatorialGames/Push-Shove/Shove.o

# target to build an object file
CombinatorialGames/Push-Shove/Shove.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGSynch_2.dir/build.make CMakeFiles/CGSynch_2.dir/CombinatorialGames/Push-Shove/Shove.cpp.o
.PHONY : CombinatorialGames/Push-Shove/Shove.cpp.o

CombinatorialGames/Push-Shove/Shove.i: CombinatorialGames/Push-Shove/Shove.cpp.i
.PHONY : CombinatorialGames/Push-Shove/Shove.i

# target to preprocess a source file
CombinatorialGames/Push-Shove/Shove.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGSynch_2.dir/build.make CMakeFiles/CGSynch_2.dir/CombinatorialGames/Push-Shove/Shove.cpp.i
.PHONY : CombinatorialGames/Push-Shove/Shove.cpp.i

CombinatorialGames/Push-Shove/Shove.s: CombinatorialGames/Push-Shove/Shove.cpp.s
.PHONY : CombinatorialGames/Push-Shove/Shove.s

# target to generate assembly for a file
CombinatorialGames/Push-Shove/Shove.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGSynch_2.dir/build.make CMakeFiles/CGSynch_2.dir/CombinatorialGames/Push-Shove/Shove.cpp.s
.PHONY : CombinatorialGames/Push-Shove/Shove.cpp.s

CombinatorialGames/RulesetUtil.o: CombinatorialGames/RulesetUtil.cpp.o
.PHONY : CombinatorialGames/RulesetUtil.o

# target to build an object file
CombinatorialGames/RulesetUtil.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGSynch_2.dir/build.make CMakeFiles/CGSynch_2.dir/CombinatorialGames/RulesetUtil.cpp.o
.PHONY : CombinatorialGames/RulesetUtil.cpp.o

CombinatorialGames/RulesetUtil.i: CombinatorialGames/RulesetUtil.cpp.i
.PHONY : CombinatorialGames/RulesetUtil.i

# target to preprocess a source file
CombinatorialGames/RulesetUtil.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGSynch_2.dir/build.make CMakeFiles/CGSynch_2.dir/CombinatorialGames/RulesetUtil.cpp.i
.PHONY : CombinatorialGames/RulesetUtil.cpp.i

CombinatorialGames/RulesetUtil.s: CombinatorialGames/RulesetUtil.cpp.s
.PHONY : CombinatorialGames/RulesetUtil.s

# target to generate assembly for a file
CombinatorialGames/RulesetUtil.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGSynch_2.dir/build.make CMakeFiles/CGSynch_2.dir/CombinatorialGames/RulesetUtil.cpp.s
.PHONY : CombinatorialGames/RulesetUtil.cpp.s

UI/Spirit/SpiritParser.o: UI/Spirit/SpiritParser.cpp.o
.PHONY : UI/Spirit/SpiritParser.o

# target to build an object file
UI/Spirit/SpiritParser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGSynch_2.dir/build.make CMakeFiles/CGSynch_2.dir/UI/Spirit/SpiritParser.cpp.o
.PHONY : UI/Spirit/SpiritParser.cpp.o

UI/Spirit/SpiritParser.i: UI/Spirit/SpiritParser.cpp.i
.PHONY : UI/Spirit/SpiritParser.i

# target to preprocess a source file
UI/Spirit/SpiritParser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGSynch_2.dir/build.make CMakeFiles/CGSynch_2.dir/UI/Spirit/SpiritParser.cpp.i
.PHONY : UI/Spirit/SpiritParser.cpp.i

UI/Spirit/SpiritParser.s: UI/Spirit/SpiritParser.cpp.s
.PHONY : UI/Spirit/SpiritParser.s

# target to generate assembly for a file
UI/Spirit/SpiritParser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGSynch_2.dir/build.make CMakeFiles/CGSynch_2.dir/UI/Spirit/SpiritParser.cpp.s
.PHONY : UI/Spirit/SpiritParser.cpp.s

UI/Spirit/TreeNodes.o: UI/Spirit/TreeNodes.cpp.o
.PHONY : UI/Spirit/TreeNodes.o

# target to build an object file
UI/Spirit/TreeNodes.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGSynch_2.dir/build.make CMakeFiles/CGSynch_2.dir/UI/Spirit/TreeNodes.cpp.o
.PHONY : UI/Spirit/TreeNodes.cpp.o

UI/Spirit/TreeNodes.i: UI/Spirit/TreeNodes.cpp.i
.PHONY : UI/Spirit/TreeNodes.i

# target to preprocess a source file
UI/Spirit/TreeNodes.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGSynch_2.dir/build.make CMakeFiles/CGSynch_2.dir/UI/Spirit/TreeNodes.cpp.i
.PHONY : UI/Spirit/TreeNodes.cpp.i

UI/Spirit/TreeNodes.s: UI/Spirit/TreeNodes.cpp.s
.PHONY : UI/Spirit/TreeNodes.s

# target to generate assembly for a file
UI/Spirit/TreeNodes.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGSynch_2.dir/build.make CMakeFiles/CGSynch_2.dir/UI/Spirit/TreeNodes.cpp.s
.PHONY : UI/Spirit/TreeNodes.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGSynch_2.dir/build.make CMakeFiles/CGSynch_2.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGSynch_2.dir/build.make CMakeFiles/CGSynch_2.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGSynch_2.dir/build.make CMakeFiles/CGSynch_2.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... CGSynch_2"
	@echo "... AbstractGame/CombinatorialGame.o"
	@echo "... AbstractGame/CombinatorialGame.i"
	@echo "... AbstractGame/CombinatorialGame.s"
	@echo "... AbstractGame/CombinatorialGameDatabase.o"
	@echo "... AbstractGame/CombinatorialGameDatabase.i"
	@echo "... AbstractGame/CombinatorialGameDatabase.s"
	@echo "... AbstractGame/DyadicRational.o"
	@echo "... AbstractGame/DyadicRational.i"
	@echo "... AbstractGame/DyadicRational.s"
	@echo "... AbstractGame/SynchronizedGameDatabase.o"
	@echo "... AbstractGame/SynchronizedGameDatabase.i"
	@echo "... AbstractGame/SynchronizedGameDatabase.s"
	@echo "... AbstractGame/SynchronousGame.o"
	@echo "... AbstractGame/SynchronousGame.i"
	@echo "... AbstractGame/SynchronousGame.s"
	@echo "... CombinatorialGames/Cherries/Cherries.o"
	@echo "... CombinatorialGames/Cherries/Cherries.i"
	@echo "... CombinatorialGames/Cherries/Cherries.s"
	@echo "... CombinatorialGames/Cherries/CherriesUtil.o"
	@echo "... CombinatorialGames/Cherries/CherriesUtil.i"
	@echo "... CombinatorialGames/Cherries/CherriesUtil.s"
	@echo "... CombinatorialGames/Cherries/StackCherries.o"
	@echo "... CombinatorialGames/Cherries/StackCherries.i"
	@echo "... CombinatorialGames/Cherries/StackCherries.s"
	@echo "... CombinatorialGames/Hackenbush/Hackenbush.o"
	@echo "... CombinatorialGames/Hackenbush/Hackenbush.i"
	@echo "... CombinatorialGames/Hackenbush/Hackenbush.s"
	@echo "... CombinatorialGames/Hackenbush/NormalGraph.o"
	@echo "... CombinatorialGames/Hackenbush/NormalGraph.i"
	@echo "... CombinatorialGames/Hackenbush/NormalGraph.s"
	@echo "... CombinatorialGames/Math/RulesetMath.o"
	@echo "... CombinatorialGames/Math/RulesetMath.i"
	@echo "... CombinatorialGames/Math/RulesetMath.s"
	@echo "... CombinatorialGames/Math/RulesetMathUtil.o"
	@echo "... CombinatorialGames/Math/RulesetMathUtil.i"
	@echo "... CombinatorialGames/Math/RulesetMathUtil.s"
	@echo "... CombinatorialGames/Push-Shove/Push.o"
	@echo "... CombinatorialGames/Push-Shove/Push.i"
	@echo "... CombinatorialGames/Push-Shove/Push.s"
	@echo "... CombinatorialGames/Push-Shove/PushShoveUtil.o"
	@echo "... CombinatorialGames/Push-Shove/PushShoveUtil.i"
	@echo "... CombinatorialGames/Push-Shove/PushShoveUtil.s"
	@echo "... CombinatorialGames/Push-Shove/Shove.o"
	@echo "... CombinatorialGames/Push-Shove/Shove.i"
	@echo "... CombinatorialGames/Push-Shove/Shove.s"
	@echo "... CombinatorialGames/RulesetUtil.o"
	@echo "... CombinatorialGames/RulesetUtil.i"
	@echo "... CombinatorialGames/RulesetUtil.s"
	@echo "... UI/Spirit/SpiritParser.o"
	@echo "... UI/Spirit/SpiritParser.i"
	@echo "... UI/Spirit/SpiritParser.s"
	@echo "... UI/Spirit/TreeNodes.o"
	@echo "... UI/Spirit/TreeNodes.i"
	@echo "... UI/Spirit/TreeNodes.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

