# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.21

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/ardour/Programs/clion-2021.1.3/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/ardour/Programs/clion-2021.1.3/bin/cmake/linux/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ardour/Documents/Uni/BSP/CGSynch/CGSynch

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ardour/Documents/Uni/BSP/CGSynch/CGSynch

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/ardour/Programs/clion-2021.1.3/bin/cmake/linux/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/ardour/Programs/clion-2021.1.3/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ardour/Documents/Uni/BSP/CGSynch/CGSynch/CMakeFiles /home/ardour/Documents/Uni/BSP/CGSynch/CGSynch//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ardour/Documents/Uni/BSP/CGSynch/CGSynch/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CGSynch_2

# Build rule for target.
CGSynch_2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CGSynch_2
.PHONY : CGSynch_2

# fast build rule for target.
CGSynch_2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGSynch_2.dir/build.make CMakeFiles/CGSynch_2.dir/build
.PHONY : CGSynch_2/fast

Game/CombinatorialGame.o: Game/CombinatorialGame.cpp.o
.PHONY : Game/CombinatorialGame.o

# target to build an object file
Game/CombinatorialGame.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGSynch_2.dir/build.make CMakeFiles/CGSynch_2.dir/Game/CombinatorialGame.cpp.o
.PHONY : Game/CombinatorialGame.cpp.o

Game/CombinatorialGame.i: Game/CombinatorialGame.cpp.i
.PHONY : Game/CombinatorialGame.i

# target to preprocess a source file
Game/CombinatorialGame.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGSynch_2.dir/build.make CMakeFiles/CGSynch_2.dir/Game/CombinatorialGame.cpp.i
.PHONY : Game/CombinatorialGame.cpp.i

Game/CombinatorialGame.s: Game/CombinatorialGame.cpp.s
.PHONY : Game/CombinatorialGame.s

# target to generate assembly for a file
Game/CombinatorialGame.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGSynch_2.dir/build.make CMakeFiles/CGSynch_2.dir/Game/CombinatorialGame.cpp.s
.PHONY : Game/CombinatorialGame.cpp.s

Game/CombinatorialGameDatabase.o: Game/CombinatorialGameDatabase.cpp.o
.PHONY : Game/CombinatorialGameDatabase.o

# target to build an object file
Game/CombinatorialGameDatabase.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGSynch_2.dir/build.make CMakeFiles/CGSynch_2.dir/Game/CombinatorialGameDatabase.cpp.o
.PHONY : Game/CombinatorialGameDatabase.cpp.o

Game/CombinatorialGameDatabase.i: Game/CombinatorialGameDatabase.cpp.i
.PHONY : Game/CombinatorialGameDatabase.i

# target to preprocess a source file
Game/CombinatorialGameDatabase.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGSynch_2.dir/build.make CMakeFiles/CGSynch_2.dir/Game/CombinatorialGameDatabase.cpp.i
.PHONY : Game/CombinatorialGameDatabase.cpp.i

Game/CombinatorialGameDatabase.s: Game/CombinatorialGameDatabase.cpp.s
.PHONY : Game/CombinatorialGameDatabase.s

# target to generate assembly for a file
Game/CombinatorialGameDatabase.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGSynch_2.dir/build.make CMakeFiles/CGSynch_2.dir/Game/CombinatorialGameDatabase.cpp.s
.PHONY : Game/CombinatorialGameDatabase.cpp.s

Game/SynchronousGame.o: Game/SynchronousGame.cpp.o
.PHONY : Game/SynchronousGame.o

# target to build an object file
Game/SynchronousGame.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGSynch_2.dir/build.make CMakeFiles/CGSynch_2.dir/Game/SynchronousGame.cpp.o
.PHONY : Game/SynchronousGame.cpp.o

Game/SynchronousGame.i: Game/SynchronousGame.cpp.i
.PHONY : Game/SynchronousGame.i

# target to preprocess a source file
Game/SynchronousGame.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGSynch_2.dir/build.make CMakeFiles/CGSynch_2.dir/Game/SynchronousGame.cpp.i
.PHONY : Game/SynchronousGame.cpp.i

Game/SynchronousGame.s: Game/SynchronousGame.cpp.s
.PHONY : Game/SynchronousGame.s

# target to generate assembly for a file
Game/SynchronousGame.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGSynch_2.dir/build.make CMakeFiles/CGSynch_2.dir/Game/SynchronousGame.cpp.s
.PHONY : Game/SynchronousGame.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGSynch_2.dir/build.make CMakeFiles/CGSynch_2.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGSynch_2.dir/build.make CMakeFiles/CGSynch_2.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CGSynch_2.dir/build.make CMakeFiles/CGSynch_2.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... CGSynch_2"
	@echo "... Game/CombinatorialGame.o"
	@echo "... Game/CombinatorialGame.i"
	@echo "... Game/CombinatorialGame.s"
	@echo "... Game/CombinatorialGameDatabase.o"
	@echo "... Game/CombinatorialGameDatabase.i"
	@echo "... Game/CombinatorialGameDatabase.s"
	@echo "... Game/SynchronousGame.o"
	@echo "... Game/SynchronousGame.i"
	@echo "... Game/SynchronousGame.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

